In [2]:
import numpy as np

### NumPy Array creation

In [4]:
x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [8]:
%timeit [j**4 for j in range(1,9)]

11.3 µs ± 1.96 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
import numpy as np 
%timeit np.arange(1,9)**4

5.18 µs ± 607 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
%timeit np.arange(1,9)**4

2.28 µs ± 645 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Array

In [12]:
x = [1,2,3,4]
y=np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
l = []
for i in range(1,5):
    int_1 = int(input('Enter :'))
    l.append(int_1)
print(np.array(l))    

Enter :12
Enter :13
Enter :14
Enter :15
[12 13 14 15]


In [16]:
# 1d_array,2d_array,3d_array
ar1 = np.array([1,2,3,4])
print(ar1)

[1 2 3 4]


In [24]:
ar2 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(ar2)
print(ar2.ndim)

[[[1 2 3 4]
  [1 2 3 4]]]
3


In [21]:
arn = np.array([1,2,3,4],ndmin=5)
print(arn)

[[[[[1 2 3 4]]]]]


In [22]:
ar3 = np.array([[1,2,3,4],[1,2,3,4]])
ar3 

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# Ones

In [25]:
ar_one = np.ones(4)
ar_one 

array([1., 1., 1., 1.])

# Empty

In [26]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


# Range

In [27]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# Diagonal

# ar_dia = np.eye(3)
print(ar_dia)


In [29]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linespace

In [31]:
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# Random

## Rand()

In [32]:
var = np.random.rand(4)
var 

array([0.81508693, 0.71902486, 0.64020082, 0.03040299])

In [46]:
var1 = np.random.randn(2,2,2)
print(var1)
print(var1.ndim)

[[[-1.16372387 -0.56864731]
  [-1.28944414 -1.05761452]]

 [[-2.39341089  0.32690324]
  [ 0.03932199  0.07544635]]]
3


## randn()

In [47]:
var2 = np.random.randn(5)
var2 

array([ 0.05415973,  1.16897522, -0.68763753, -0.36696153,  0.20755431])

## randf()

In [48]:
var3 = np.random.ranf(4) 
var3 

array([0.33732872, 0.28759287, 0.97019345, 0.46045536])

## randint()

In [50]:
var4 = np.random.randint(5,20,5)
print(var4)

[14  8 16 16 16]


# Numpy DataType

In [51]:
var = np.array([1,2,3,4])
print('Data type :',var.dtype)


Data type : int32


In [52]:
var = np.array([1.2,2,3,4])
print('Data type :',var.dtype)


Data type : float64


In [53]:
var = np.array([1.2,'Hello',3,4])
print('Data type :',var.dtype)


Data type : <U32


In [55]:
var = np.array(['a','b'])
print('Data type :',var.dtype)


Data type : <U1


In [56]:
var = np.array(['a','bo'])
print('Data type :',var.dtype)


Data type : <U2


In [77]:
x = np.array([1,2,3,4])
print(x.dtype)
#convert to float
x1 = np.array([1,2,3,4,5],dtype='f')
xc = np.array([1,2,3,4,5],dtype='c') #complex float

print(x1)
print(x1.dtype)
print(xc)
print(xc.dtype)

int32
[1. 2. 3. 4. 5.]
float32
[b'1' b'2' b'3' b'4' b'5']
|S1


In [64]:
# use as a function
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new1 = np.int_(x2)

print(x2)
print(new)
print(new1)

[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [69]:
# change type
x3 = np.array([1,2,3,4])
new2 = x3.astype(complex)
print(x3)
print(new2)


[1 2 3 4]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


# Airthmetic Operation


In [79]:
import numpy as np 
var = np.array([1,2,3,4])
varadd = var +3
print(varadd)

[4 5 6 7]


In [82]:
var2 = np.array([1,2,3,4])
var1 = np.array([1,2,3,4])

varadd = var1+var2 
vardiv = var1/var2
vardiv_1 = var1 /3 

print(varadd)
print(vardiv)
print(vardiv_1)

[2 4 6 8]
[1. 1. 1. 1.]
[0.33333333 0.66666667 1.         1.33333333]


In [88]:
# 2d array
var21 = np.array([[1,2,3],[1,2]])
var22 = np.array([[1,2,3],[1,2]])

varadd2 = var21 + var22
print(varadd2)

[list([1, 2, 3, 1, 2, 3]) list([1, 2, 1, 2])]


In [89]:
# 2d array
var21 = np.array([[1,2],[1,2]])
var22 = np.array([[1,2],[1,2]])

varadd2 = var21 + var22
print(varadd2)

[[2 4]
 [2 4]]


In [97]:
# Airthmetic function
var = np.array([1,2,3,4,5,6])
print('min :',np.min(var))
print('max :',np.max(var))
print('argmin :',np.argmin(var))
print('cumnsum :',np.cumsum(var))
print('sqrt :',np.sqrt(var))
print('sin :',np.sin(var))

min : 1
max : 6
argmin : 0
cumnsum : [ 1  3  6 10 15 21]
sqrt : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
sin : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [95]:
# 2d array
var1 = np.array([[2,1,8],[9,5,6]])
print(np.min(var1,axis=1)) #rowwise
print(np.min(var1,axis=0)) #column wise

[1 5]
[2 1 6]


# Shape & Reshape

In [106]:
var = np.array([[1,2,5],[1,2]])
print(var)
print(var.shape)
print(type(var))

[list([1, 2, 5]) list([1, 2])]
(2,)
<class 'numpy.ndarray'>


In [112]:
var1 = np.array([[1,2,3],[1,2,3]],ndmin=4)
print(var1)
print(var1.shape)

[[[[1 2 3]
   [1 2 3]]]]
(1, 1, 2, 3)


In [114]:
var1 = np.array([1,2,3],ndmin=4)
print(var1)
print(var1.shape)

[[[[1 2 3]]]]
(1, 1, 1, 3)


In [118]:
#Reshape
var2 = np.array([1,2,3,4,5,6])
x = var2.reshape(2,3)
print(x)
print(var2.ndim)
print(x.ndim)

[[1 2 3]
 [4 5 6]]
1
2


In [126]:
# 3d array reshaping
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x3 = var3.reshape(2,3,2)
print(x3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Broadcastig

In [127]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
print(var1+var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [132]:
var = np.array([1,2,3])
var1 = var.reshape(3,1)
print(var1)
print(var1.shape)
var2 = var.reshape(1,3)
print(var2)
print(var2.shape)
      
print()
print(var1+var2)

[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]
(1, 3)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [133]:
var1 = np.array([[1],[2]])
var2 = np.array([[1,2,3],[1,2,3]])
print(var1+var2)

[[2 3 4]
 [3 4 5]]


# Indexing and Slicing

In [134]:
#1d
var = np.array([1,2,3,4,5])
print(var[1])

2


In [139]:
#2d
var2d = np.array([[1,9,6],[1,2,5]])
print(var2d)
print(var2d.ndim)
print(var2d[1][1])
print(var2d[0,1])
print(var2d[0][1])

[[1 9 6]
 [1 2 5]]
2
2
9
9


In [145]:
#3d
var3d = np.array([[[1,2],[1,2]],[[7,8],[7,8]]])
print(var3d)
print(var3d.ndim)
print()
print(var3d[1,1,1])

[[[1 2]
  [1 2]]

 [[7 8]
  [7 8]]]
3

8


In [154]:
#Slicing
x = np.array([1,2,3,4,5,4,5])
print(x[1:10:2])
print(x[2:]) #up to end
print(x[:4]) # up to 4
print(x[::])
print(x[::2])

[2 4 4]
[3 4 5 4 5]
[1 2 3 4]
[1 2 3 4 5 4 5]
[1 3 5 5]


In [160]:
# 2d slicing
var2 = np.array([[1,2,3,4],[5,6,7,9],[22,33,44,11]])
print(var2)
print(var2.ndim)
print()
print('fetch 6 to 9 :',var2[1,1:])

[[ 1  2  3  4]
 [ 5  6  7  9]
 [22 33 44 11]]
2

fetch 6 to 9 : [6 7 9]


In [164]:
# 3d slicing
var2 = np.array([[[1,2,3,4],[5,6,7,9],[22,33,44,11]]])
print(var2)
print(var2.ndim)
print()
#print('fetch 6 to 9 :',var2[1,1:])
print('fetch 6 to 9 :',var2[0,1,1:])

[[[ 1  2  3  4]
  [ 5  6  7  9]
  [22 33 44 11]]]
3

fetch 6 to 9 : [33 44 11]


In [168]:
# 3d slicing
var2 = np.array([[[1,2,3,4],[5,6,7,9],[22,33,44,11]],[[9,8,7,4],[4,4,4,4],[220,330,440,110]]])
print(var2)
print(var2.ndim)
print()
print('fetch 330 to 110 :',var2[1,2,1:])

[[[  1   2   3   4]
  [  5   6   7   9]
  [ 22  33  44  11]]

 [[  9   8   7   4]
  [  4   4   4   4]
  [220 330 440 110]]]
3

fetch 330 to 110 : [330 440 110]


# Iteration of Numpy Array

In [170]:
x = np.array([8,4,5,6,7,9])
print(x)
for i in x:
    print(i)
    

[8 4 5 6 7 9]
8
4
5
6
7
9


In [174]:
var2 = np.array([[1,2,3],[1,2,3]])
print(var2)
print()
for j in var2:
    print(j)
print()
#seprate all elements
for i in var2:
    for j in i:
        print(j)

[[1 2 3]
 [1 2 3]]

[1 2 3]
[1 2 3]

1
2
3
1
2
3


In [195]:
#3d array itration
var3 = np.array([[[1,2,3],[1,1,1]]])
print(var3)
print(var3.ndim)
print('**********')
print(var3[0,1:])
print()
for i in var3:
    print(i)
    print()
    for j in i:
        for k in j:
            print(k)


[[[1 2 3]
  [1 1 1]]]
3
**********
[[1 1 1]]

[[1 2 3]
 [1 1 1]]

1
2
3
1
1
1


In [202]:
# nditer()
var3 = np.array([[[3,3,3,3],[1,2,3,4]]])
print(var3)
print(var3.ndim)
for i in np.nditer(var3,flags = ['buffered'],op_dtypes=["S"]):
    print(i)
print('*********************')
for i in np.nditer(var3):
    print(i)
print('*********************')
for i,d in np.ndenumerate(var3):
    print(i,d)


[[[3 3 3 3]
  [1 2 3 4]]]
3
b'3'
b'3'
b'3'
b'3'
b'1'
b'2'
b'3'
b'4'
*********************
3
3
3
3
1
2
3
4
*********************
(0, 0, 0) 3
(0, 0, 1) 3
(0, 0, 2) 3
(0, 0, 3) 3
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


# Copy vs Views

In [207]:
x = np.array([1,2,3,4])
x_copy = x.copy()

print(x_copy)
x_view = x.view()
print(x_view)
print('***************')
x[1]=40
print(x_copy)
print(x_view)




[1 2 3 4]
[1 2 3 4]
***************
[1 2 3 4]
[ 1 40  3  4]


# Join & Split Arrays

In [210]:
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

ar = np.concatenate((var,var1))
print(ar)
print(var+var1)

[1 2 3 4 9 8 7 6]
[10 10 10 10]


In [215]:
#2d array 
var2 = np.array([[1,2],[3,4]])
print(var2)
var3 = np.array([[9,8],[9,9]])
print(var3)
ar_new = np.concatenate((var2,var3),axis=1)
print('******************')
print(ar_new)
ar_newc = np.concatenate((var2,var3),axis=0)
print('******************')
print(ar_newc)

[[1 2]
 [3 4]]
[[9 8]
 [9 9]]
******************
[[1 2 9 8]
 [3 4 9 9]]
******************
[[1 2]
 [3 4]
 [9 8]
 [9 9]]


In [224]:
#stack
var2 = np.array([1,2,3,4])
var3 = np.array([5,6,7,8])

a_new = np.stack((var2,var3),axis=1)
print(a_new)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [222]:
#stack
var2 = np.array([1,2,3,4])
var3 = np.array([5,6,7,8])

a_new = np.stack((var2,var3),axis=0)
print(a_new)

[[1 2 3 4]
 [5 6 7 8]]


In [225]:
#hstack
var2 = np.array([1,2,3,4])
var3 = np.array([5,6,7,8])

a_new = np.hstack((var2,var3)) #rowwise stack
print(a_new)

[1 2 3 4 5 6 7 8]


In [226]:
#vstack
var2 = np.array([1,2,3,4])
var3 = np.array([5,6,7,8])

a_new = np.vstack((var2,var3)) #column stack
print(a_new)

[[1 2 3 4]
 [5 6 7 8]]


In [227]:
#dstack
var2 = np.array([1,2,3,4])
var3 = np.array([5,6,7,8])

a_new = np.dstack((var2,var3)) #height stack
print(a_new)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [230]:
#Array_split
var = np.array([1,2,3,4,5,6])
print(var)
print()
ar_split = np.array_split(var,3)
print(ar_split)
print(ar_split[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [235]:
# split on 2d array
var2d = np.array([[1,2],[3,4],[5,6]])
print(var)
varrd_split = np.array_split(var2d,4)
print(varrd_split)
varrd_split2 = np.array_split(var2d,3,axis=1)
print(varrd_split2)


[1 2 3 4 5 6]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([], shape=(0, 2), dtype=int32)]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]


# Functions

search, sort ,filter, Shuffle, Unique, Resize,Flatten, Ravel

In [236]:
#search - at which index
var = np.array([1,2,3,4,5,6,7,8,4])
search_4 = np.where(var==4)
print(search_4)

(array([3, 8], dtype=int64),)


In [238]:
var = np.array([1,2,3,4,5,6,7,8,4,22])
even = np.where(var%2==0)
print(even)

(array([1, 3, 5, 7, 8, 9], dtype=int64),)


In [247]:
#search sort array
var = np.array([1,3,4,6,7,8])# it should be sorted
x1 = np.searchsorted(var,5) # this works left to right
print(x1)

3


In [246]:
#search sort array
var = np.array([1,2,3,4,6,7,8,9,19])# it should be sorted
x1 = np.searchsorted(var,5,side='right') # this works right to left
print(x1)

4


In [248]:
var = np.array([1,2,3,4,6,7,8,9,19])# it should be sorted
x1 = np.searchsorted(var,[5,6,7]) # this works right to left
print(x1)

[4 4 5]


In [252]:
#sort array
var_1 = np.array([1,2,3,4,22,6,7,8,9,19])
print(np.sort(var_1))


[ 1  2  3  4  6  7  8  9 19 22]


In [253]:
var_1 = np.array([1,'a',2,3,4,22,6,7,8,9,19])
print(np.sort(var_1))

['1' '19' '2' '22' '3' '4' '6' '7' '8' '9' 'a']


In [254]:
#2d array sort
var_1 = np.array([[4,2],[3,4],[22,6],[7,8],[9,19]])
print(np.sort(var_1))

[[ 2  4]
 [ 3  4]
 [ 6 22]
 [ 7  8]
 [ 9 19]]


In [257]:
#Filter
var_3 = np.array(['a','b','c','d'])
f = [True,False,True,True]
new_a = var_3[f] #it will return teuw array
print(new_a)
print(type(new_a))

['a' 'c' 'd']
<class 'numpy.ndarray'>


In [260]:
#shuffle
var = np.array([1,2,3,4,22,6,7,8,9,19])
np.random.shuffle(var)
print(var)

[ 1 19  9  3  6  7  4  8  2 22]


In [263]:
#Unique
var = np.array([1,2,3,4,22,6,7,8,9,19,4,5,4])
print(np.unique(var))


[ 1  2  3  4  5  6  7  8  9 19 22]


In [265]:
#Unique with index and counts
var = np.array([1,2,3,4,22,6,7,8,9,19,4,5,4])
print(np.unique(var,return_index=True,return_counts=True))


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 19, 22]), array([ 0,  1,  2,  3, 11,  5,  6,  7,  8,  9,  4], dtype=int64), array([1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1], dtype=int64))


In [269]:
#Resize
var = np.array([1,2,3,4,22,6,7,8,9,19,4,5,4])
y = np.resize(var,(2,8))
print(y)

[[ 1  2  3  4 22  6  7  8]
 [ 9 19  4  5  4  1  2  3]]


In [273]:
#Flatten
var = np.array([1,2,3,4,22,6,7,8,9,19,4,5,4])
y = np.resize(var,(2,8))
print(y)
print()
print(y.flatten())
print()
print(y.flatten(order='F'))
print()
print(y.flatten(order='A'))
print()
print(y.flatten(order='K'))

[[ 1  2  3  4 22  6  7  8]
 [ 9 19  4  5  4  1  2  3]]

[ 1  2  3  4 22  6  7  8  9 19  4  5  4  1  2  3]

[ 1  9  2 19  3  4  4  5 22  4  6  1  7  2  8  3]

[ 1  2  3  4 22  6  7  8  9 19  4  5  4  1  2  3]

[ 1  2  3  4 22  6  7  8  9 19  4  5  4  1  2  3]


In [278]:
#ravel
print(np.ravel(y,order = 'F'))
print(np.ravel(y))

[ 1  9  2 19  3  4  4  5 22  4  6  1  7  2  8  3]
[ 1  2  3  4 22  6  7  8  9 19  4  5  4  1  2  3]


# Insert and Delete

In [289]:
# insert - it will insert only integer value
var = np.array([1,2,3,4,5,6,7])
v =np.insert(var,1,[99,88]) # insert at single position
print(v)
v1 =np.insert(var,(1,6),99) # insert at multiple position
print(v1)

[ 1 99 88  2  3  4  5  6  7]
[ 1 99  2  3  4  5  6 99  7]


In [297]:
# insert at 2d array
var2 = np.array([[1,2],[3,4]])
v1 = np.insert(var2,1,99)# it will flat
print(v1)
print()
v1 = np.insert(var2,1,99,axis=0)# it will add row
print(v1)
print()
v1 = np.insert(var2,1,[11,99],axis=0)# it will add row
print(v1)
print()
v1 = np.insert(var2,1,99,axis=1)# it will add column
print(v1)

[ 1 99  2  3  4]

[[ 1  2]
 [99 99]
 [ 3  4]]

[[ 1  2]
 [11 99]
 [ 3  4]]

[[ 1 99  2]
 [ 3 99  4]]


In [300]:
#append
var = np.array([1,2,3,4,5,6,7])
v =np.append(var,6.5)
print(v)


[1.  2.  3.  4.  5.  6.  7.  6.5]


In [308]:
var2 = np.array([[1,2],[3,4]])
v2 = np.append(var2,[[1,9]],axis=0)

print(v2)
print("************")
v2 = np.append(var2,[[1,9]],axis=1) # why not working

print(v2)

[[1 2]
 [3 4]
 [1 9]]
************


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [309]:
#delete - index wise deletion
var = np.array([1,2,3,4,5,6,7])
v_del = np.delete(var,4)
print(v_del)

[1 2 3 4 6 7]


# Matrix

In [318]:
m1 = np.matrix([[1,2],[3,4]])
m2 = np.matrix([[1,2],[3,4]])
print(m1.dot(m2))
print(m1*m2)

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [321]:
#Transpose
m1 = np.matrix([[1,2],[3,4]])
print(m1)
print()
print(np.transpose(m1))
print(m1.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [324]:
# swapaxes
m1 = np.matrix([[1,2],[3,4]])
print(m1)
print(np.swapaxes(m1,1,0))



[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [327]:
#Inverse
m1 = np.matrix([[1,2],[3,4]])
print(np.linalg.inv(m1))


[[-2.   1. ]
 [ 1.5 -0.5]]


In [331]:
#Power
m1 = np.matrix([[1,2],[3,4]])
print(np.linalg.matrix_power(m1,0))
print()
print(np.linalg.matrix_power(m1,-2))
print()
print(np.linalg.matrix_power(m1,2))

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]

[[ 7 10]
 [15 22]]


In [337]:
#Determinate
m1 = np.matrix([[1,2,3,4],[3,4,4,1],[1,1,2,3],[1,3,2,3]])
print(np.linalg.det(m1))

-12.000000000000005
